name: foodpanda_clone
description: A Flutter Food Delivery app (FoodPanda-style) with Firebase backend and multi-role support.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management & navigation
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.2.7

  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.1
  firebase_messaging: ^15.1.3
  google_sign_in: ^6.2.1

  # Maps & location
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.2

  # Payments
  flutter_stripe: ^11.0.0

  # UI/UX
  lottie: ^3.1.3
  cached_network_image: ^3.4.1
  intl: ^0.19.0

  # Utils
  uuid: ^4.5.1
  dio: ^5.7.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  riverpod_generator: ^2.3.11
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/

